### ISSUE TITLE
Align use of `arc_specification` package

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-validate-package-registry#67]
1. Where do I find the `arc_specification` validation packages (e.g. `arc_specification: 2.0.0-draft`) 
2. I'd suggest to list them in https://avpr.nfdi4plants.org/packages
3. I'd suggest to align the validation of ARCs with those of other packages, e.g. 

instead of 
```
arc_specification: 2.0.0-draft
validation_packages:
  - name: invenio
    version: 2.1.0
```
do
```
validation_packages:
  - name: arc_specification
    version: 2.0.0-draft
  - name: invenio
    version: 2.1.0
```
